# Generated by Django 4.1.2 on 2022-10-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='c_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='characters',
            name='c_name',
            field=models.CharField(max_length=50),
        ),
    ]
