# Generated by Django 4.1.2 on 2022-10-27 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_characters_c_image_alter_characters_c_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characters',
            name='c_image',
        ),
    ]
